CREATE TABLE "customers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "city" varchar,
  "preferences" jsonb
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "category" varchar,
  "price" decimal
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "order_date" date DEFAULT CURRENT_DATE,
  "total" decimal
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int,
  "subtotal" decimal
);

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

CREATE TABLE "products_order_items" (
  "products_id" int,
  "order_items_product_id" int,
  PRIMARY KEY ("products_id", "order_items_product_id")
);

ALTER TABLE "products_order_items" ADD FOREIGN KEY ("products_id") REFERENCES "products" ("id");

ALTER TABLE "products_order_items" ADD FOREIGN KEY ("order_items_product_id") REFERENCES "order_items" ("product_id");

